services:
  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "88:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: quetz
      POSTGRES_PASSWORD: quetz
      POSTGRES_DB: quetz
    volumes:
      - /data/beta-mamba-pm/test/postgres:/var/lib/postgresql/data

  quetz:
    build: .
    depends_on:
      - db
    labels:
      - "traefik.http.routers.web.rule=Host(`127.0.0.1`)"
      - "traefik.http.services.web.loadbalancer.server.port=8000"
    volumes:
    - .:/workspace:cached
    - /data/beta-mamba-pm/test/quetz:/data
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

#volumes:
#  db-data:
