services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quetz
    volumes:
      - ./data/prod/postgres:/var/lib/postgresql/data

  quetz:
    image: beta-mamba-pm-quetz
    depends_on:
      - db
    volumes:
      - .:/workspace:cached
      - ./data/prod/quetz:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/prod/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/prod/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - quetz