name: quetz
channels:
  - conda-forge
dependencies:
#  - quetz
  - nodejs=16
  - yarn=1.22
  - sqlalchemy
  - sqlalchemy-utils
  - conda-build<=24.1.2
  - conda-index
  - psycopg2
  - xattr
  - python>=3.7
  - pip
  - fastapi
  - typer >=0.9,<1.0
  - authlib=0.15.5
  - psycopg2
  - httpx>=0.22.0
  - sqlalchemy
  - sqlalchemy-utils
  - sqlite
  - python-multipart
  - uvicorn
  - zstandard
  - conda-build
  - appdirs
  - toml
  - fsspec
  - requests
  - h2
  - pluggy
  - jinja2
  - itsdangerous
  - alembic
  - zchunk
  - s3fs
  - gcsfs >=2022.03
  - sphinx
  - sphinx-book-theme>=0.3
  - tenacity
  - xattr
  - aiofiles
  - aioshutil
  - pyyaml
  - ujson
  - prometheus_client
  - pamela
  - typing_extensions
  - adlfs
  - importlib_metadata
  - pre-commit
  - pytest 7.*
  - pytest-mock
  - rq
  - libcflib
  - mamba
  - conda-content-trust
  - pyinstrument
  - pytest-asyncio
  - pytest-timeout
  - pydantic >=2
  - boto3
  - python-dotenv
  - awscli
  - ansible
  - ansible-lint
  - ovh
  - mamba
  - python-novaclient
  - python-swiftclient
  - python-octaviaclient
